//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicatie_medicala.Data_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrare
    {
        public System.Guid IDTratament { get; set; }
        public System.DateTime Data_ora { get; set; }
        public string CNP_personal { get; set; }
    
        public virtual Tratament Tratament { get; set; }
    }
}
