//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicatie_medicala.Data_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnostic
    {
        public Diagnostic()
        {
            this.Trataments = new HashSet<Tratament>();
        }
    
        public System.Guid IDDiagnostic { get; set; }
        public System.Guid IDInreg { get; set; }
        public string Nume { get; set; }
    
        public virtual Internari_Externari Internari_Externari { get; set; }
        public virtual ICollection<Tratament> Trataments { get; set; }
    }
}
