//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicatie_medicala.Data_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Internari_Externari
    {
        public Internari_Externari()
        {
            this.Diagnostics = new HashSet<Diagnostic>();
        }
    
        public System.Guid IDInreg { get; set; }
        public string CNP { get; set; }
        public System.DateTime Data_internare { get; set; }
        public Nullable<System.DateTime> Data_externare { get; set; }
        public string CNP_Medic { get; set; }
    
        public virtual ICollection<Diagnostic> Diagnostics { get; set; }
        public virtual Pacienti Pacienti { get; set; }
        public virtual Personal Personal { get; set; }
    }
}
