//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicatie_medicala.Data_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacienti
    {
        public Pacienti()
        {
            this.Internari_Externari = new HashSet<Internari_Externari>();
        }
    
        public string CNP { get; set; }
        public string Nume { get; set; }
        public string Prenume { get; set; }
        public Nullable<int> Varsta { get; set; }
        public string Adresa { get; set; }
        public string Telefon { get; set; }
        public string Email { get; set; }
        public bool Internat { get; set; }
    
        public virtual ICollection<Internari_Externari> Internari_Externari { get; set; }
    }
}
