//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicatie_medicala.Data_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permisiuni
    {
        public Permisiuni()
        {
            this.Categories = new HashSet<Categorie>();
        }
    
        public int IDPerm { get; set; }
        public string Nume { get; set; }
    
        public virtual ICollection<Categorie> Categories { get; set; }
    }
}
