//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicatie_medicala.Data_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        public Personal()
        {
            this.Internari_Externari = new HashSet<Internari_Externari>();
        }
    
        public string CNP { get; set; }
        public int IDCateg { get; set; }
        public string Nume { get; set; }
        public string Prenume { get; set; }
        public string Adresa { get; set; }
        public string Telefon { get; set; }
        public int IDSectie { get; set; }
        public System.DateTime Data_angajare { get; set; }
        public Nullable<System.DateTime> Data_incheiere { get; set; }
        public double Salariu { get; set; }
        public byte[] Parola { get; set; }
    
        public virtual Categorie Categorie { get; set; }
        public virtual ICollection<Internari_Externari> Internari_Externari { get; set; }
        public virtual Sectii Sectii { get; set; }
    }
}
