//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicatie_medicala.Data_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tratament
    {
        public Tratament()
        {
            this.Administrares = new HashSet<Administrare>();
        }
    
        public System.Guid IDTratament { get; set; }
        public System.Guid IDDiagnostic { get; set; }
        public string Medicament { get; set; }
        public string Administare { get; set; }
    
        public virtual ICollection<Administrare> Administrares { get; set; }
        public virtual Diagnostic Diagnostic { get; set; }
    }
}
